### ISSUE TITLE
Faded icons

### ISSUE THREAD

**Issue by wizardshill** [vyadh/teamcity-deployment-dashboard#10] opened 2019-07-12 16:56 UTC
What is the significants between the bright and faded icons?
There seems to be no rhyme or reason for it.

![Screen Shot 2019-07-12 at 9 52 37 AM](https://user-images.githubusercontent.com/9683200/61144991-3ea63480-a48b-11e9-97b0-f586fe7510df.png)

**Comment by vyadh** [comment] 2019-07-12 21:34
This is probably not as well explained in the readme as I'd like, but here are the appropriate sections:

> Highlights the latest version to emphasise build journey to production (assuming semver-formatted version string).

and 

> This can be any formatted version string, but in order to visualise the journey of the build through environments it interprets the version number to work out which is the latest build and de-emphasises any deployments that are not. This is why in the screenshot above the older builds are slightly faded, to keep emphasis on a new build moving towards production.

In your screenshot above, it's showing your "latest" version. The top two rows have the same number, so it shows this version has gone from the 1st environment to the 2nd.

In the other rows the middle is the latest by version number. Not sure what's happening in the 3rd row (the versions being very different) but the last two rows suggest your second column is the 1st environment you deploy to, the first column being the 2nd? The idea is that you specify the environments in the configuration in the order you deploy them to, e.g. DEV -> UAT -> PROD.

This does assume that your environments do constitute a journey to production of course - it was one of the main reasons I wrote it for my usage :) If you're just deploying to multiple targets, I suppose it then just shows you where your latest version is.

**Comment by vyadh** [comment] 2019-07-12 21:55
I'll close this like the other one as it's intended behaviour, but feel free to explain your use-case and we can re-open if necessary.

**Closed as completed** 2019-07-12 21:57 UTC

**Comment by wizardshill** [comment] 2019-07-12 22:44
Ahh, yes... I see it now... lol
thanks
